### ISSUE TITLE
Error in example code for I2C LCD

### ISSUE THREAD

**Issue by Peacemaker47** [CytronTechnologies/MAKER-PI-PICO#10]
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "LCD_I2C.py", line 57, in __init__
  File "LCD_I2C.py", line 107, in _command
OSError: [Errno 5] EIO

**Comment by Bhavithiran97** [comment]
Which lcd modulw are you using ?
This library is for
https://www.cytron.io/p-3v3-i2c-and-spi-1602-serial-character-lcd?tracking=b-py

You may look the library documentation here
https://github.com/Bhavithiran97/LCM1602-14_LCD_Library
